package Wzorce.WzorceProjektowe.Day4.TemplateMethod.Before;

public class adoasd {
    public static void main(String[] args) {
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SdadDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
        System.out.println("SDAD");
    }
}
